// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooabimdnvzplczqgklcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vYWJpbWRudnpwbGN6cWdrbGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDk3MDIsImV4cCI6MjA3MzIyNTcwMn0.MrN0r8JPTU4D8JxEytnnmVJoCiZGc_isZpO-mDZZJsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});